"""create core tables

Revision ID: b6187da16e99
Revises: 
Create Date: 2026-09-03 14:48:41.372071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6187da16e99'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('license_number', sa.String(length=30), nullable=False),
    sa.Column('status', sa.Enum('active', 'on_leave', 'off_duty', name='driver_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plate_number', sa.String(length=20), nullable=False),
    sa.Column('vehicle_type', sa.String(length=30), nullable=False),
    sa.Column('capacity_kg', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('available', 'in_use', 'maintenance', name='vehicle_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plate_number')
    )
    op.create_table('shipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracking_number', sa.String(length=40), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_transit', 'delivered', 'cancelled', name='shipment_status'), nullable=False),
    sa.Column('scheduled_pickup', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scheduled_delivery', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_pickup', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_delivery', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tracking_number')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.Enum('predicted_delay', 'weather_risk', 'capacity_overload', 'route_blocked', name='alert_type'), nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', name='alert_severity'), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shipment_id', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=150), nullable=False),
    sa.Column('destination', sa.String(length=150), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('estimated_duration_min', sa.Integer(), nullable=False),
    sa.Column('weather_risk_flag', sa.Boolean(), nullable=False),
    sa.Column('traffic_risk_flag', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shipment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('routes')
    op.drop_table('alerts')
    op.drop_table('shipments')
    op.drop_table('vehicles')
    op.drop_table('drivers')
    # ### end Alembic commands ###

    # Manually added: Postgres ENUM types are separate objects and aren't
    # dropped automatically when the tables that use them are dropped.
    # Without this, re-running `upgrade` after a `downgrade` fails with
    # "type ... already exists".
    bind = op.get_bind()
    sa.Enum(name='driver_status').drop(bind, checkfirst=True)
    sa.Enum(name='vehicle_status').drop(bind, checkfirst=True)
    sa.Enum(name='shipment_status').drop(bind, checkfirst=True)
    sa.Enum(name='alert_type').drop(bind, checkfirst=True)
    sa.Enum(name='alert_severity').drop(bind, checkfirst=True)
